"""Migrate all data from SQLite to Supabase PostgreSQL via REST API."""
import sqlite3
import json
import sys
import time

import httpx

import os
SUPABASE_URL = os.getenv("SUPABASE_URL", "")
SUPABASE_KEY = os.getenv("SUPABASE_KEY", "")
if not SUPABASE_URL or not SUPABASE_KEY:
    raise SystemExit("Set SUPABASE_URL and SUPABASE_KEY environment variables.")

HEADERS = {
    "apikey": SUPABASE_KEY,
    "Authorization": f"Bearer {SUPABASE_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=minimal",
}

SQLITE_PATH = "caratsense.db"

# Tables in dependency order (parents first)
TABLES = [
    "articles",
    "users",
    "buyers",
    "racks",
    "stock_entries",
    "sales",
    "purchases",
    "audit_logs",
    "offers",
    "followups",
]

# Columns to skip (auto-generated by Postgres)
SKIP_COLS = {}


def get_sqlite_data(table):
    conn = sqlite3.connect(SQLITE_PATH)
    conn.row_factory = sqlite3.Row
    rows = conn.execute(f"SELECT * FROM {table}").fetchall()
    conn.close()
    return rows


def clean_row(row_dict):
    """Clean a row for Supabase insertion."""
    cleaned = {}
    for k, v in row_dict.items():
        if v is None:
            cleaned[k] = None
        elif isinstance(v, (int, float)):
            cleaned[k] = v
        else:
            cleaned[k] = str(v)
    return cleaned


def migrate_table(table, batch_size=500):
    rows = get_sqlite_data(table)
    if not rows:
        print(f"  {table}: 0 rows (skip)")
        return 0

    total = len(rows)
    uploaded = 0
    errors = 0

    # Convert rows to dicts, exclude 'id' to let Postgres auto-generate
    all_data = []
    for r in rows:
        d = clean_row(dict(r))
        # Remove id — let Supabase auto-generate serial IDs
        # But we NEED to keep IDs for foreign key references
        all_data.append(d)

    # Upload in batches
    client = httpx.Client(timeout=60)
    for i in range(0, total, batch_size):
        batch = all_data[i:i + batch_size]
        try:
            resp = client.post(
                f"{SUPABASE_URL}/rest/v1/{table}",
                headers={**HEADERS, "Prefer": "return=minimal,resolution=merge-duplicates"},
                json=batch,
            )
            if resp.status_code in (200, 201):
                uploaded += len(batch)
            else:
                # Try one by one for failed batch
                for row in batch:
                    try:
                        r2 = client.post(
                            f"{SUPABASE_URL}/rest/v1/{table}",
                            headers=HEADERS,
                            json=row,
                        )
                        if r2.status_code in (200, 201):
                            uploaded += 1
                        else:
                            errors += 1
                            if errors <= 3:
                                print(f"    Error: {r2.status_code} - {r2.text[:100]}")
                    except Exception as e:
                        errors += 1
        except Exception as e:
            print(f"    Batch error: {e}")
            errors += len(batch)

        # Progress
        pct = min(100, (i + batch_size) * 100 // total)
        print(f"  {table}: {min(uploaded + errors, total)}/{total} ({pct}%)", end="\r")

    client.close()
    print(f"  {table}: {uploaded} uploaded, {errors} errors (total {total})")
    return uploaded


def reset_sequences():
    """Reset auto-increment sequences to max(id) + 1."""
    print("\nResetting sequences...")
    client = httpx.Client(timeout=30)
    for table in TABLES:
        try:
            # Get max ID
            resp = client.get(
                f"{SUPABASE_URL}/rest/v1/{table}?select=id&order=id.desc&limit=1",
                headers=HEADERS,
            )
            if resp.status_code == 200:
                data = resp.json()
                if data:
                    max_id = data[0]["id"]
                    # We can't run raw SQL via REST, but the sequences will auto-adjust
                    print(f"  {table}: max_id = {max_id}")
        except Exception:
            pass
    client.close()


def main():
    print("=" * 60)
    print("CaratSense: SQLite -> Supabase Migration")
    print("=" * 60)
    print(f"Source: {SQLITE_PATH}")
    print(f"Target: {SUPABASE_URL}")
    print()

    total_uploaded = 0
    for table in TABLES:
        uploaded = migrate_table(table)
        total_uploaded += uploaded

    reset_sequences()

    print()
    print("=" * 60)
    print(f"Migration complete! {total_uploaded:,} total rows uploaded.")
    print("=" * 60)

    # Verify counts
    print("\nVerification:")
    client = httpx.Client(timeout=30)
    for table in TABLES:
        try:
            resp = client.get(
                f"{SUPABASE_URL}/rest/v1/{table}?select=id&limit=1",
                headers={**HEADERS, "Prefer": "count=exact"},
            )
            count = resp.headers.get("content-range", "?")
            print(f"  {table}: {count}")
        except Exception as e:
            print(f"  {table}: error - {e}")
    client.close()


if __name__ == "__main__":
    main()
