"""End-Of-Day Summary — generates WhatsApp-ready EOD report."""
from datetime import date, timedelta

from fastapi import APIRouter, Depends
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.models.sales import Sale
from app.models.stock import StockEntry
from app.models.buyers import Buyer
from app.models.tasks import Task

router = APIRouter(prefix="/eod", tags=["eod"])


@router.get("/summary")
async def eod_summary(db: AsyncSession = Depends(get_db)):
    """Generate today's EOD summary with WhatsApp-ready text."""
    today = date.today()
    yesterday = today - timedelta(days=1)

    # Today's sales
    sales_today = await db.execute(
        select(
            func.count(Sale.id),
            func.coalesce(func.sum(Sale.quantity_meters), 0),
            func.coalesce(func.sum(Sale.total_amount), 0),
        ).where(Sale.voucher_date == today)
    )
    st = sales_today.one()

    # Stock status
    stock = await db.execute(
        select(
            func.count(StockEntry.id),
            func.coalesce(func.sum(StockEntry.meters), 0),
        ).where(StockEntry.status == "available")
    )
    sk = stock.one()

    # Critical aging
    critical = await db.execute(
        select(func.count(StockEntry.id))
        .where(StockEntry.status == "available", StockEntry.aging_days > 90)
    )
    cr = critical.scalar()

    # Active buyers today
    active_today = await db.execute(
        select(func.count(func.distinct(Sale.buyer_id)))
        .where(Sale.voucher_date == today)
    )
    at = active_today.scalar()

    # Tasks status
    tasks_pending = await db.execute(
        select(func.count(Task.id)).where(Task.status == "pending")
    )
    tp = tasks_pending.scalar()

    tasks_completed_today = await db.execute(
        select(func.count(Task.id))
        .where(Task.status == "completed", func.date(Task.completed_at) == today)
    )
    tc = tasks_completed_today.scalar()

    # Build WhatsApp message
    whatsapp_text = f"""📊 *CaratSense EOD Report — {today}*
━━━━━━━━━━━━━━━━━━━

💰 *Today's Sales:*
   Orders: {st[0]}
   Meters: {float(st[1]):,.0f}m
   Revenue: Rs.{float(st[2]):,.0f}

📦 *Stock Status:*
   Available: {sk[0]:,} lots ({float(sk[1]):,.0f}m)
   Critical aging (90d+): {cr:,} items

👥 *Buyers:*
   Active today: {at}

✅ *Tasks:*
   Pending: {tp}
   Completed today: {tc}

━━━━━━━━━━━━━━━━━━━
_Auto-generated by CaratSense_"""

    return {
        "date": str(today),
        "sales": {"orders": st[0], "meters": float(st[1]), "revenue": float(st[2])},
        "stock": {"lots": sk[0], "meters": float(sk[1]), "critical_aging": cr},
        "buyers_active_today": at,
        "tasks": {"pending": tp, "completed_today": tc},
        "whatsapp_text": whatsapp_text,
    }
