"""PDF Invoice generation from sales data."""
import io
from datetime import date

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.models.sales import Sale

router = APIRouter(prefix="/invoice", tags=["invoice"])


@router.get("/{sale_id}")
async def generate_invoice(sale_id: int, db: AsyncSession = Depends(get_db)):
    result = await db.execute(select(Sale).where(Sale.id == sale_id))
    sale = result.scalar_one_or_none()
    if not sale:
        raise HTTPException(status_code=404, detail="Sale not found")

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=20*mm, rightMargin=20*mm, topMargin=20*mm, bottomMargin=20*mm)
    styles = getSampleStyleSheet()
    elements = []

    # Header
    elements.append(Paragraph("<b>CaratSense Surplus Stock</b>", styles['Title']))
    elements.append(Paragraph("Tax Invoice", styles['Heading2']))
    elements.append(Spacer(1, 10*mm))

    # Invoice details
    buyer_name = sale.buyer.name if sale.buyer else "N/A"
    article_code = sale.article.article_code if sale.article else "N/A"

    info_data = [
        ["Invoice No:", sale.voucher_number or f"INV-{sale.id}", "Date:", str(sale.voucher_date or date.today())],
        ["Buyer:", buyer_name, "Sale Type:", sale.sale_type or "dyed"],
    ]
    info_table = Table(info_data, colWidths=[80, 170, 80, 170])
    info_table.setStyle(TableStyle([
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTNAME', (2, 0), (2, -1), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ]))
    elements.append(info_table)
    elements.append(Spacer(1, 8*mm))

    # Line items
    items_data = [["Article", "Batch", "Pcs", "Meters", "Rate", "Amount"]]
    items_data.append([
        article_code,
        sale.batch_number or "-",
        str(sale.quantity_pieces or "-"),
        f"{sale.quantity_meters or 0:,.1f}",
        f"₹{sale.unit_price or 0:,.2f}" if sale.unit_price else "-",
        f"₹{sale.total_amount or 0:,.2f}" if sale.total_amount else "-",
    ])

    items_table = Table(items_data, colWidths=[100, 100, 40, 60, 70, 80])
    items_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.Color(0.15, 0.16, 0.2)),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.Color(0.8, 0.8, 0.8)),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('ALIGN', (2, 0), (-1, -1), 'RIGHT'),
    ]))
    elements.append(items_table)
    elements.append(Spacer(1, 10*mm))

    # Negotiation info
    if sale.buyer_offer_price or sale.final_price:
        neg_data = []
        if sale.buyer_offer_price:
            neg_data.append(["Buyer Offer:", f"₹{sale.buyer_offer_price:,.2f}/m"])
        if sale.final_price:
            neg_data.append(["Final Price:", f"₹{sale.final_price:,.2f}/m"])
        if sale.buyer_offer_price and sale.final_price and sale.buyer_offer_price > 0:
            discount = (1 - sale.final_price / sale.buyer_offer_price) * 100
            neg_data.append(["Discount:", f"{discount:.1f}%"])
        neg_table = Table(neg_data, colWidths=[100, 150])
        neg_table.setStyle(TableStyle([
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ]))
        elements.append(neg_table)
        elements.append(Spacer(1, 5*mm))

    # Footer
    elements.append(Spacer(1, 15*mm))
    elements.append(Paragraph("Generated by CaratSense Surplus Stock Platform", styles['Normal']))

    doc.build(elements)
    buf.seek(0)

    filename = f"invoice_{sale.voucher_number or sale.id}_{date.today()}.pdf"
    return StreamingResponse(buf, media_type="application/pdf",
                             headers={"Content-Disposition": f'attachment; filename="{filename}"'})
